//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prachin_Bangpakong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AltitudeData
    {
        public int ID_AltitudeData { get; set; }
        public string CodeStation { get; set; }
        public string MinDo { get; set; }
        public string MaxDo { get; set; }
        public string MinConductivity { get; set; }
        public string MaxConductivity { get; set; }
        public string MinpH { get; set; }
        public string MaxpH { get; set; }
        public string MinTemp { get; set; }
        public string MaxTemp { get; set; }
        public string MinSalinity { get; set; }
        public string MaxSalinity { get; set; }
        public string MinSolution { get; set; }
        public string MaxSolution { get; set; }
        public string MinLevel_water { get; set; }
        public string MaxLevel_water { get; set; }
        public string MinFlow { get; set; }
        public string MaxFlow { get; set; }
        public string MinVelocity { get; set; }
        public string MaxVelocity { get; set; }
        public string Note { get; set; }
        public string StationName { get; set; }
    }
}
