//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prachin_Bangpakong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class station
    {
        public int IDStation { get; set; }
        public string SerialSim { get; set; }
        public string Ime { get; set; }
        public string Codestation { get; set; }
        public string StationName { get; set; }
        public string Lat { get; set; }
        public string Long { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Levelwater_Offset { get; set; }
        public Nullable<bool> HL4_Installed { get; set; }
        public Nullable<bool> HLD_Installed { get; set; }
        public string Note { get; set; }
        public string Entrance { get; set; }
        public Nullable<bool> StatusShow { get; set; }
    }
}
